<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CardCollections.Application\CardCollections.Application.csproj" />
    <ProjectReference Include="..\src\CardCollections.Domain\CardCollections.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Repositories\" />
  </ItemGroup>

</Project>
